### ISSUE TITLE
How does @nuxtjs/proxy work with nuxt + express ?

### ISSUE THREAD

**Issue by wushan** [nuxt-community/modules#168]
I have use @nuxtjs/proxy on a starter project of nuxt, It looks nice to help me separating the enviorment between different enviroments, But when I am using express, the proxy function seems never worked again.

I've saw the similar post here #36 which didn't solve my problem.

Does anybody using this ?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/modules/issues/c99">#c99</a>)</em></sub></div>

**Comment by microcipcip** [comment]
I was having this problem as well, I have fixed this by using nuxt starter kit instead of nuxt express, then I created a `myproject/api/` folder and created an express instance there myself, then on nuxt.config I added:

```
  modules: [
    '@nuxtjs/proxy'
  ],
  proxy: {
    '/api': 'http://localhost:3001',
    ws: true
  },
```

`myproject/api/index.js` is basically something like this:
```
import express from 'express'
import routes from './routes'

const host = process.env.HOST || '127.0.0.1'
const port = process.env.PORT || 3001
const app = express()
app.use('/api', routes)
app.listen(port, host)
```
`myproject/api/backpack.config.js` is:
```
const path = require('path')
module.exports = {
  webpack: (config, options, webpack) => {
    config.entry.main = './index.js'
    config.resolve.alias = {
      root: path.resolve(__dirname, './'),
      controllers: path.resolve(__dirname, './controllers/'),
      models: path.resolve(__dirname, './models/'),
      routes: path.resolve(__dirname, './routes/')
    }
    return config
  }
}
```
`myproject/api/package.json` is:
```
...
 "dependencies": {
    "express": "^4.15.3"
  },
  "devDependencies": {
    "backpack-core": "^0.4.1"
  }
...
```

The only problem is that you have to run two node servers, one for nuxt and one for express, but you avoid the 5seconds rebuild in this way.

**Comment by anteriovieira** [comment]
I am closing this question by understanding that the doubt has been answered. Anything follow the [documentation](https://nuxtjs.org/api/nuxt-render#nuxt-render-req-res-).
