### ISSUE TITLE
@nuxtjs/toast Not working in server context

### ISSUE THREAD

**Issue by Zsavajji** [nuxt-community/modules#206]
Hi, 
i'm trying to send a toast into a middleware which checks auth status. I wanted it to set a toast and redirect if the user is not logged, but i get an undefined error on app.$toast. I thought i could access $toast on the context.app, what am i doing wrong?

```
export default ({ store, app, redirect }) => {
  if(store.getters['user/isUserLogged']) {
    app.$toast.show('Already registered!');
    return redirect({ name: 'homepage' })
  }
}
```
Thanks

**Comment by rbraddev** [comment]
Did you guys manage to get this working?

**Comment by sltsm** [comment]
Same Issue. Any updates?

**Comment by williamweckl** [comment]
+1

**Comment by luminous8** [comment]
Same issue on my side

**Comment by remigermain** [comment]
any new of this ?

**Comment by Lacroute** [comment]
Same issue

**Comment by Lacroute** [comment]
In fact, that makes sense to don't be able to toast on server side. But It's tricky when I have to deal with api requests inside `nuxtServerInit` action. So I ended up with this solution:

```
// inside @/plugins/axiosToats.js

export default function ({ $axios, app }) {
  $axios.onError((error) => {
    console.log(error.response)
    if (process.client) {
      app.$toast.error('Error while making request: ' + error.response.data)
    }
  })
}
```

**Comment by enzolry** [comment]
I found the solution in this topic https://github.com/nuxt/nuxt.js/issues/2653#issuecomment-414551760

I use a mixin to handle my auth check on client side. But with this solution, there is a small delay before reaching mounted() hook so the restricted component is visible for a short time. So I added a loading state in my store to show a loading screen until mounted() hook is reached.

/stores/auth.js
```javascript
export const state = () => ({
    loggedIn: false,
    loading: true
})

export const mutations = {
    toggleLoading: state => {
        state.loading = !state.loading
    }
}
```
/layouts/default.vue
```vue
<template>
  <div>
    <Header />
    <main v-if="loading">
      <div class="container">
        <p>Loading...</p>
      </div>
    </main>
    <main v-else>
      <Nuxt />
    </main>
  </div>
</template>

<script>
export default {
  computed: {
    loading(){
      return this.$store.state.auth.loading
    }
  },
  mounted(){
    this.$store.commit('auth/toggleLoading')
  }
}
</script>
```

/mixins/auth.js
```javascript
export default {
    mounted(){
        if(!this.$store.state.auth.loggedIn){
            this.$toast.error('Unauthorized access.')
            this.$router.push('/login')
        }
    }
}
```

/pages/dashboard.vue
```javascript
import auth from '../mixins/auth'

export default {
    mixins: [auth]
}
```

**Comment by vallecbg** [comment]
Using this solution I'm still struggling with the delay of showing the content for a second. It's not showing the "loading..." text.

**Comment by enzolry** [comment]
> Using this solution I'm still struggling with the delay of showing the content for a second. It's not showing the "loading..." text.

Well, seeing my answer a few month later I can tell that it's actually not a good idea to put the `<Nuxt />` tag inside a v-else because it will reload all sub-components each time you change the "loading" state. The "loading..." text can stay inside the `<main>` tag but it shouldn't be a v-if statement and it could be styled with "position:fixed" and "z-index:9999" to simply show above and hide the rest of the content whenever "loading" state is true.

Also, instead of using mounted() hook to change "loading" value, you could try to add a watcher on "$fetchState.pending" inside layouts/default.vue and wait it's set back to false to know that all data has been fetched. Maybe you don't see the "loading..." text because you don't have to wait for a server response and it's too fast to see. If you really want to see it you can add a fake delay with a setTimeout() and change the "loading" value inside the callback.

**Comment by vallecbg** [comment]
It's not working on mine. I think I am missing something. Can you show me an example, please?
